version: '2.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - mongodb:/data/db
  weather-service:
    image: weathersvc-dev:latest
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "1337:1337"
    depends_on: 
      - mongo
  app:
    image: weathernow-app-dev:latest
    restart: always
    environment: 
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
      - weather-service
    volumes: 
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/src/public
volumes:
  mongodb:
