apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    stage: production
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        stage: production
        name: webapp
    spec:
      containers:
        - image: asia.gcr.io/inbound-trilogy-217503/weathernow-app-prod:latest
          imagePullPolicy: "Always"
          name: app
          resources:
            limits:
              cpu: "0.5"
              memory: "450M"
            requests:
              cpu: "0.25"
              memory: "400M"
          env:
            - name: NODE_ENV
              value: production
          ports:
            - containerPort: 80
              name: app-port
      restartPolicy: Always
