apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    stage: production
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    stage: production
    name: mongo-pod