apiVersion: v1
kind: Service
metadata:
  name: weathersvc-service
  labels:
    stage: production
spec:
  selector:
    stage: production
    name: weatherservice-pod
  type: LoadBalancer
  ports:
  - name: 'secure-port'
    port: 443
    targetPort: 443
  - name: 'open-port'
    port: 80
    targetPort: 80