apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  labels:
    stage: production
    name: mongo-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
